name: usb-reset
version: '0.3'
summary: Reset a USB device using vendor and product ID.
description: This tool allows you to perform a bus reset on a USB device
    connected to your system. If the device has got confused, this may sort it
    out.
    You will need to use "sudo snap connect usb-reset:raw-usb core:raw-usb" and
    "sudo snap connect usb-reset:hardware-observe core:hardware-observe" to
    give this snap access to USB devices.
confinement: strict
grade: stable
base: core20

apps:
  usb-reset:
    command: usr/local/bin/usb-reset
    plugs: [hardware-observe, raw-usb]

parts:
  usb-reset:
    plugin: make
    source: https://github.com/ralight/usb-reset
    source-type: git

    build-packages:
      - gcc
      - libusb-1.0-0-dev

    stage-packages:
      - libusb-1.0-0

    prime:
    - usr/local/bin/usb-reset
    - lib/*-linux-gnu/libusb-1.0.so*
